PROGRAMS += lws_lib_test_compression

########## OS DETECTION
UNAME_S := $(shell uname -s 2>/dev/null || echo Windows)

ifeq ($(UNAME_S),Linux)
    OS_NAME := Linux
else ifeq ($(UNAME_S),Darwin)
    OS_NAME := Mac
else
    OS_NAME := Windows
    ARCH ?= x64
    OS_NAME := $(OS_NAME)-$(ARCH)
endif

#######################


LWS_TEST_BUILD_ZLIB = $(BUILD_DIR)/lws_lib_test_compression

# LibWebSockets files generated by BUILD_LWS.
LWS_TEST_INSTALL_ZLIB = \
	src/external/libwebsockets/$(OS_NAME)

# Used to check if the file exist before build
ifeq ($(findstring Windows,$(OS_NAME)),Windows)
    LWS_TEST_LIBRARY_ZLIB = $(LWS_TEST_INSTALL_ZLIB)/lib/libwebsockets_static.a
else
    LWS_TEST_LIBRARY_ZLIB = $(LWS_TEST_INSTALL_ZLIB)/lib/libwebsockets.a
endif


#######################
########### LINKER/FLAG
LDFLAGS_LWS_TEST_ZLIB = -L$(LWS_TEST_INSTALL_ZLIB)/lib

ifeq ($(OS_NAME),Linux)
  LDLIBS_LWS_TEST_ZLIB = -lwebsockets -lmbedtls -lmbedx509 -lmbedcrypto -lz -lnghttp2 -lpthread -ldl -lm
else ifeq ($(OS_NAME),Mac)
  LDLIBS_LWS_TEST_ZLIB = -lwebsockets -lmbedtls -lmbedx509 -lmbedcrypto -lz -lnghttp2 -lpthread
else ifeq ($(findstring Windows,$(OS_NAME)),Windows)
  LDLIBS_LWS_TEST_ZLIB = -lwebsockets_static -lmbedtls -lmbedx509 -lmbedcrypto -lz -lnghttp2 -lws2_32 -luserenv -lcrypt32 -liphlpapi
endif



# Allow lws_lib_test.cpp to include:
#   #include <libwebsockets.h>
CPPFLAGS_LWS_TEST_ZLIB = \
	-I$(LWS_TEST_INSTALL_ZLIB)/include

# Static LWS applications on Windows must define LWS_STATICLIB.
ifeq ($(findstring Windows,$(OS_NAME)),Windows)
	CPPFLAGS_LWS_TEST_ZLIB += -DLWS_STATICLIB
endif

#######################

# COMMON OBJECTS
LWS_TEST_OBJ_ZLIB = \
	$(LWS_TEST_BUILD_ZLIB)/test_libwebsockets_lib_with_compression.o

## BUILD
# IMPORTANT: The libwebsocket MUST BE BUILT BEFORE !!!

$(LWS_TEST_BUILD_ZLIB):
	@mkdir -p $@

$(LWS_TEST_LIBRARY_ZLIB):
	$(error libwebsockets library not found: $(LWS_TEST_LIBRARY_ZLIB))
	#@echo "libwebsockets.a not found. Building dependencies..."
	#$(MAKE) -C MakefileFolder/libwebsockets_build

# Create objects from C++ sources
$(LWS_TEST_BUILD_ZLIB)/%.o: src/unit_test/%.cpp | $(LWS_TEST_BUILD_ZLIB)
	$(CXX) -c $< $(CPPFLAGS_LWS_TEST_ZLIB) $(CXXFLAGS) -o $@


# Build the final executable with all object
lws_lib_test_compression: $(LWS_TEST_OBJ_ZLIB) $(LWS_TEST_LIBRARY_ZLIB)
ifeq ($(findstring Windows,$(OS_NAME)),Windows)
	$(CXX) $(LDFLAGS) $(WINDOWS_STATIC_LDFLAGS) $(LDFLAGS_LWS_TEST_ZLIB) $(LWS_TEST_OBJ_ZLIB) $(LDLIBS_LWS_TEST_ZLIB) $(LDLIBS) -o $@.exe
else
	$(CXX) $(LDFLAGS) $(LDFLAGS_LWS_TEST_ZLIB) $(LWS_TEST_OBJ_ZLIB) $(LDLIBS_LWS_TEST_ZLIB) $(LDLIBS) -o $@
endif

#---
clean-lws-test-zlib:
	rm -rf $(LWS_TEST_BUILD_ZLIB) lws_lib_test_compression lws_lib_test_compression.exe


.PHONY: clean-lws-test-zlib



$(info LWS_TEST_BUILD_ZLIB=$(LWS_TEST_BUILD_ZLIB))
$(info LWS_TEST_OBJ_ZLIB=$(LWS_TEST_OBJ_ZLIB))
$(info SRC=$(wildcard src/unit_test/*.cpp))


