PROGRAMS += lws_lib_test

########## OS DETECTION
UNAME_S := $(shell uname -s 2>/dev/null || echo Windows)

ifeq ($(UNAME_S),Linux)
    OS_NAME := Linux
else ifeq ($(UNAME_S),Darwin)
    OS_NAME := Mac
else
    OS_NAME := Windows
    ARCH ?= x64
    OS_NAME := $(OS_NAME)-$(ARCH)
endif

#######################


LWS_TEST_BUILD = $(BUILD_DIR)/lws_lib_test

# LibWebSockets files generated by BUILD_LWS.
LWS_TEST_INSTALL = \
	src/external/libwebsockets/$(OS_NAME)

# Used to check if the file exist before build
ifeq ($(findstring Windows,$(OS_NAME)),Windows)
    LWS_TEST_LIBRARY = $(LWS_TEST_INSTALL)/lib/libwebsockets_static.a
else
    LWS_TEST_LIBRARY = $(LWS_TEST_INSTALL)/lib/libwebsockets.a
endif


#######################
########### LINKER/FLAG
LDFLAGS_LWS_TEST = -L$(LWS_TEST_INSTALL)/lib

ifeq ($(OS_NAME),Linux)
  LDLIBS_LWS_TEST = -lwebsockets -lmbedtls -lmbedx509 -lmbedcrypto -lz -lnghttp2 -lpthread -ldl -lm
else ifeq ($(OS_NAME),Mac)
  LDLIBS_LWS_TEST = -lwebsockets -lmbedtls -lmbedx509 -lmbedcrypto -lz -lnghttp2 -lpthread
else ifeq ($(findstring Windows,$(OS_NAME)),Windows)
  LDLIBS_LWS_TEST = -lwebsockets_static -lmbedtls -lmbedx509 -lmbedcrypto -lz -lnghttp2 -lws2_32 -luserenv -lcrypt32 -liphlpapi
endif



# Allow lws_lib_test.cpp to include:
#   #include <libwebsockets.h>
CPPFLAGS_LWS_TEST = \
	-I$(LWS_TEST_INSTALL)/include

# Static LWS applications on Windows must define LWS_STATICLIB.
ifeq ($(findstring Windows,$(OS_NAME)),Windows)
	CPPFLAGS_LWS_TEST += -DLWS_STATICLIB
endif

#######################

# COMMON OBJECTS
LWS_TEST_OBJ = \
	$(LWS_TEST_BUILD)/test_libwebsockets_lib.o

## BUILD
# IMPORTANT: The libwebsocket MUST BE BUILT BEFORE !!!

$(LWS_TEST_BUILD):
	@mkdir -p $@

$(LWS_TEST_LIBRARY):
	$(error libwebsockets library not found: $(LWS_TEST_LIBRARY))
	#@echo "libwebsockets.a not found. Building dependencies..."
	#$(MAKE) -C MakefileFolder/libwebsockets_build

# Create objects from C++ sources
$(LWS_TEST_BUILD)/%.o: src/unit_test/%.cpp | $(LWS_TEST_BUILD)
	$(CXX) -c $< $(CPPFLAGS_LWS_TEST) $(CXXFLAGS) -o $@


# Build the final executable with all object
lws_lib_test: $(LWS_TEST_OBJ) $(LWS_TEST_LIBRARY)
ifeq ($(findstring Windows,$(OS_NAME)),Windows)
	$(CXX) $(LDFLAGS) $(WINDOWS_STATIC_LDFLAGS) $(LDFLAGS_LWS_TEST) $(LWS_TEST_OBJ) $(LDLIBS_LWS_TEST) $(LDLIBS) -o $@.exe
else
	$(CXX) $(LDFLAGS) $(LDFLAGS_LWS_TEST) $(LWS_TEST_OBJ) $(LDLIBS_LWS_TEST) $(LDLIBS) -o $@
endif

#---
clean-lws-test:
	rm -rf $(LWS_TEST_BUILD) lws_lib_test lws_lib_test.exe


.PHONY: clean-lws-test



$(info LWS_TEST_BUILD=$(LWS_TEST_BUILD))
$(info LWS_TEST_OBJ=$(LWS_TEST_OBJ))
$(info SRC=$(wildcard src/unit_test/*.cpp))


